version: '3'

services:
  app:
    container_name: app
    build:
      context: .docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - net_clinic

  nginx:
    container_name: nginx
    restart: always
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./src/:/var/www
    depends_on:
      - app
    networks:
      - net_clinic
  # db:
  #   container_name: db
  #   ports:
  #     -3306:3306
  #   volumes:
  #     - .docker

  # phpmyadmin:
  #   image: phpmyadmin
  #   environment:
  #     - PMA_HOST=db
  #     - MYSQL_ROOT_PASSWORD=root
  #     - PMA_ARBITRARY=1
  #   ports:
  #     -8080:80

networks:
  net_clinic:
    driver: bridge